### ISSUE TITLE
Cannot get historical emails

### ISSUE THREAD

**Issue by ghost** [tempmail-lol/api-python#10]
Hi Mr Alexander,

I'm one of TempMail Plus users. 

When using TempMail Web, I could always get my historical emails. But recently when using Python SKD, for a certain email, I could only get the email once, and then I would not get the email. 

I checked all your python codes I cannot find anything about historical emails. Is there anyway that I could get my historical email?

Thank you!

**Comment by AlexanderEpolite** [comment]
When you receive an email from the TempMail API, it is deleted.  You will need to store your emails on your computer/server.  The web version of TempMail also only receives them once, but it stores the emails in localStorage on the web browser.
