### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CodecNomad** [tempmail-lol/api-python#4]
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", lp0\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Inbox is not JSON serializable

**Comment by AlexanderEpolite** [comment]
Hello,

Are you still experiencing this issue?

**Comment by Khali001** [comment]
yep

**Comment by aimarket** [comment]
I believe the code has been updated. are you still experiencing this?

**Comment by AlexanderEpolite** [comment]
@CodecNomad is this still an issue?  If not, I'll be closing the issue.
CC: @Khali001

**Comment by CodecNomad** [comment]
> @CodecNomad is this still an issue?  If not, I'll be closing the issue.
> CC: @Khali001 
> 

I don't know; I gave up on the project I wanted to do.
