### ISSUE TITLE
Update the Python to use v2 of the TempMail API

### ISSUE THREAD

**Issue by AlexanderEpolite** [tempmail-lol/api-python#7]
Once the v2 API is released, the Python API will be updated to use the latest version

**Comment by aimarket** [comment]
i this still ongoing? or has it already been updated

**Comment by AlexanderEpolite** [comment]
> i this still ongoing? or has it already been updated

Still ongoing, going to finish TempMail Accounts before this is prioritized.

**Comment by aimarket** [comment]
I created a branch
[branch for v2](https://github.com/tempmail-lol/api-python/tree/7-update-the-python-to-use-v2-of-the-tempmail-api)
